DROP TABLE IF EXISTS "REVATUREROOT"."BANKUSER";
CREATE TABLE "REVATUREROOT"."BANKUSER" 
   ("BANKUID" NUMBER, 
	"USERNAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PASSWD" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("BANKUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
DROP TABLE IF EXISTS "REVATUREROOT"."PERMISSION";
CREATE TABLE "REVATUREROOT"."PERMISSION" 
   (	"PERMISSION" VARCHAR2(40 BYTE), 
	 PRIMARY KEY ("PERMISSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  INSERT INTO "REVATUREROOT"."PERMISSION" VALUES ('BANK_EMPLOYEE');
  INSERT INTO "REVATUREROOT"."PERMISSION" VALUES ('BANK_ADMIN');
  
DROP TABLE IF EXISTS "REVATUREROOT"."USER_PERMISSION";
CREATE TABLE "REVATUREROOT"."USER_PERMISSION" 
   (	"BANKUID" NUMBER, 
	"PERMISSION" VARCHAR2(40 BYTE), 
	 PRIMARY KEY ("BANKUID", "PERMISSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("BANKUID")
	  REFERENCES "REVATUREROOT"."BANKUSER" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("PERMISSION")
	  REFERENCES "REVATUREROOT"."PERMISSION" ("PERMISSION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

DROP TABLE IF EXISTS "REVATUREROOT"."BANKACCOUNTTYPE";
CREATE TABLE "REVATUREROOT"."BANKACCOUNTTYPE" 
   (	"ACCOUNTTYPE" VARCHAR2(40 BYTE), 
	 PRIMARY KEY ("ACCOUNTTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
INSERT INTO "REVATUREROOT"."BANKACCOUNTTYPE" VALUES ('ACCT_CHECK');
INSERT INTO "REVATUREROOT"."BANKACCOUNTTYPE" VALUES ('ACCT_SAVE');
INSERT INTO "REVATUREROOT"."BANKACCOUNTTYPE" VALUES ('APPLY_CHECK');
INSERT INTO "REVATUREROOT"."BANKACCOUNTTYPE" VALUES ('APPLY_SAVE');

DROP TABLE IF EXISTS "REVATUREROOT"."BANKACCOUNT";
CREATE TABLE "REVATUREROOT"."BANKACCOUNT" 
   (	"BANKUID" NUMBER, 
	"ACCTTYPE" VARCHAR2(40 BYTE), 
	"AMOUNT" FLOAT(126), 
	 PRIMARY KEY ("BANKUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("ACCTTYPE")
	  REFERENCES "REVATUREROOT"."BANKACCOUNTTYPE" ("ACCOUNTTYPE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
DROP TABLE IF EXISTS "REVATUREROOT"."USER_ACCOUNT";
CREATE TABLE "REVATUREROOT"."USER_ACCOUNT" 
   (	"USERUID" NUMBER, 
	"ACCTUID" NUMBER, 
	 PRIMARY KEY ("USERUID", "ACCTUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("USERUID")
	  REFERENCES "REVATUREROOT"."BANKUSER" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("ACCTUID")
	  REFERENCES "REVATUREROOT"."BANKACCOUNT" ("BANKUID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
DROP TABLE IF EXISTS "REVATUREROOT"."TRANSTYPE";
CREATE TABLE "REVATUREROOT"."TRANSTYPE" 
   (	"TRANSTYPE" VARCHAR2(40 BYTE), 
	 PRIMARY KEY ("TRANSTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
INSERT INTO "REVATUREROOT"."TRANSTYPE" VALUES('TRANS_DEPOSIT');
INSERT INTO "REVATUREROOT"."TRANSTYPE" VALUES('TRANS_WITHDRAW');


DROP TABLE IF EXISTS "REVATUREROOT"."BANKTRANS";
CREATE TABLE "REVATUREROOT"."BANKTRANS" 
   (	"TRANSUID" NUMBER, 
	"USERUID" NUMBER, 
	"ACCOUNTUID" NUMBER, 
	"TRANSTYPE" VARCHAR2(40 BYTE), 
	"AMOUNT" FLOAT(126), 
	"TRANSDAY" DATE, 
	"TRANSTIME" TIMESTAMP (6) WITH TIME ZONE, 
	 PRIMARY KEY ("TRANSUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("USERUID")
	  REFERENCES "REVATUREROOT"."BANKUSER" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("ACCOUNTUID")
	  REFERENCES "REVATUREROOT"."BANKACCOUNT" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("TRANSTYPE")
	  REFERENCES "REVATUREROOT"."TRANSTYPE" ("TRANSTYPE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;