DROP TABLE BANKUSER CASCADE CONSTRAINTS;
CREATE TABLE BANKUSER 
   ("BANKUID" NUMBER, 
	"USERNAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PASSWD" VARCHAR2(256 BYTE), 
	 PRIMARY KEY ("BANKUID")
   );
   
CREATE OR REPLACE PROCEDURE new_user   
(   neo_uid IN BANKUSER.BANKUID%TYPE,
    neo_name IN BANKUSER.USERNAME%TYPE,
	neo_password IN BANKUSER.PASSWD%TYPE
)
IS
BEGIN
    INSERT INTO BANKUSER(BANKUID, USERNAME, PASSWD) VALUES (neo_uid, neo_name, neo_password);
END;
 
EXEC new_user(0, 'BigMoney', '$2a$10$hwLbjzKYDVaZDJHma1ioee8NkLbLnhF0tlnNo/r5GmbWyi2QpOQw6');
 
DROP TABLE PERMISSION CASCADE CONSTRAINTS;
CREATE TABLE PERMISSION 
   (	PERMISSION NUMBER PRIMARY KEY
   );
  INSERT INTO PERMISSION VALUES (0);
  INSERT INTO PERMISSION VALUES (1);
  
DROP TABLE USER_PERMISSION CASCADE CONSTRAINTS;
CREATE TABLE USER_PERMISSION   
  (	
     BANKUID NUMBER NOT NULL, 
	 PERMISSION NUMBER NOT NULL, 
	 PRIMARY KEY ("BANKUID", "PERMISSION"),
	 FOREIGN KEY ("BANKUID")
	  REFERENCES BANKUSER("BANKUID"), 
	 FOREIGN KEY ("PERMISSION")
	  REFERENCES PERMISSION ("PERMISSION") 
  );

DROP TABLE BANKACCOUNTTYPE CASCADE CONSTRAINTS;
CREATE TABLE BANKACCOUNTTYPE 
   (	"ACCOUNTTYPE" VARCHAR2(40 BYTE) PRIMARY KEY, 
        "BANKUID"     NUMBER NOT NULL
   );
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('ACCT_CHECK', 1);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('ACCT_SAVE', 0);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('APPLY_CHECK', 2);
INSERT INTO BANKACCOUNTTYPE (ACCOUNTTYPE, BANKUID) VALUES ('APPLY_SAVE', 3);

DROP TABLE "REVATUREROOT"."BANKACCOUNT" CASCADE CONSTRAINTS;
CREATE TABLE "REVATUREROOT"."BANKACCOUNT" 
   (	"BANKUID" NUMBER, 
	"ACCTTYPE" NUMBER, 
	"AMOUNT" FLOAT(126), 
	 PRIMARY KEY ("BANKUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("ACCTTYPE")
	  REFERENCES "REVATUREROOT"."BANKACCOUNTTYPE" ("BANKUID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
CREATE TABLE USER_ACCOUNT 
   (	"USERUID" NUMBER, 
	"ACCTUID" NUMBER, 
	 PRIMARY KEY ("USERUID", "ACCTUID"),
	 FOREIGN KEY ("USERUID")
	  REFERENCES BANKUSER ("BANKUID"), 
	 FOREIGN KEY ("ACCTUID")
	  REFERENCES BANKACCOUNT ("BANKUID")
   );
  
DROP TABLE "REVATUREROOT"."TRANSTYPE" CASCADE CONSTRAINTS;
CREATE TABLE "REVATUREROOT"."TRANSTYPE" 
   (	"TRANSTYPE" VARCHAR2(40 BYTE), 
		"TRANSID"   NUMBER NOT NULL,
	 PRIMARY KEY ("TRANSTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
INSERT INTO "REVATUREROOT"."TRANSTYPE" VALUES('TRANS_DEPOSIT', 1);
INSERT INTO "REVATUREROOT"."TRANSTYPE" VALUES('TRANS_WITHDRAW', 0);


DROP TABLE "REVATUREROOT"."BANKTRANS" CASCADE CONSTRAINTS;
CREATE TABLE "REVATUREROOT"."BANKTRANS" 
   (	"TRANSUID" NUMBER, 
	"USERUID" NUMBER NOT NULL, 
	"ACCOUNTUID" NUMBER NOT NULL, 
	"TRANSTYPE" NUMBER NOT NULL, 
	"AMOUNT" FLOAT(126), 
	"TRANSDAY" DATE, 
	"TRANSTIME" TIMESTAMP (6) WITH TIME ZONE, 
	 PRIMARY KEY ("TRANSUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("USERUID")
	  REFERENCES "REVATUREROOT"."BANKUSER" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("ACCOUNTUID")
	  REFERENCES "REVATUREROOT"."BANKACCOUNT" ("BANKUID") ENABLE, 
	 FOREIGN KEY ("TRANSTYPE")
	  REFERENCES "REVATUREROOT"."TRANSTYPE" ("TRANSID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;